[build]
  functions = "functions"

[[redirects]]
  to="/.netlify/functions/index/:splat"
  from="/*/"
  status=200
  force=true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"